### 1. Aim

To understand impact of promotional activities on Merchandise Sales for Zara

<ol> 
    <li> Which categories were promoted the most compared to others? </li>
    <li> How many products were promoted in each section ? </li>
    <li> Which category brings high sales? </li>
    <li> Total products and Total products per category</li>
    <li> Top 2 expensive products in each category </li>
    <li> Do men shop more than women in Zara? </li>

</ol>

### 2. Installing necessary libraries

In [1]:
import numpy as np
import pandas as pd

### 3. About the dataset
The dataset is sourced from <a href = "https://www.kaggle.com/datasets/xontoloyo/data-penjualan-zara">Kaggle </a>

### 4. Importing the dataset

In [2]:
df = pd.read_csv('zara.csv', sep = ';')

In [3]:
# Glimpse of dataset
df.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product ID        252 non-null    int64
 1   Product Position  252 non-null    object
 2   Promotion         252 non-null    object
 3   Product Category  252 non-null    object
 4   Seasonal          252 non-null    object
 5   Sales Volume      252 non-null    int64
 6   brand             252 non-null    object
 7   url               252 non-null    object
 8   sku               252 non-null    object
 9   name              251 non-null    object
 10  description       250 non-null    object
 11  price             252 non-null    float64
 12  currency          252 non-null    object
 13  scraped_at        252 non-null    object
 14  terms             252 non-null    object
 15  section           252 non-null    object
dtypes: float64(1), int64(2), object(13)
memory usage: 31.6+ KB

In [5]:
# Datatypes
df.dtypes

Product ID            int64
Product Position     object
Promotion            object
Product Category     object
Seasonal             object
Sales Volume          int64
brand                object
url                  object
sku                  object
name                 object
description          object
price               float64
currency             object
scraped_at           object
terms                object
section              object
dtype: object

In [6]:
# Total number of rows and columns
df.shape

(252, 16)

### 5. Cleaning Stage

In [7]:
## update date time datatype
df['scraped_at'] = pd.to_datetime(df['scraped_at']).dt.date

In [8]:
## Rename columns
df = df.rename(columns = {'terms':'category'})

In [9]:
## Drop a column
df = df.drop(columns = ['Product ID'])

### 6. Exploratory data analysis & Insights

In [10]:
# What are categories of clothes in merchandise
df['category'].unique()

array(['jackets', 'shoes', 'sweaters', 'jeans', 't-shirts'], dtype=object)

In [11]:
## What are unique type of Jackets?
df[df['category'] == 'jackets']['name']

0                                BASIC PUFFER JACKET
1                                      TUXEDO JACKET
2                               SLIM FIT SUIT JACKET
3                                STRETCH SUIT JACKET
4                                DOUBLE FACED JACKET
                           ...
247    FAUX LEATHER OVERSIZED JACKET LIMITED EDITION
248                CONTRASTING PATCHES BOMBER JACKET
249                              PATCH BOMBER JACKET
250            CROPPED BOMBER JACKET LIMITED EDITION
251                       FAUX LEATHER PUFFER JACKET
Name: name, Length: 140, dtype: object

In [12]:
## What are different types of shoes?
df[df['category'] == 'shoes']['name']

130             SUEDE FISHERMAN SANDALS
131          ZIPPER MULTIPIECE SNEAKERS
132             SUEDE LACELESS SNEAKERS
133                 MULTICOLOR SNEAKERS
134              RETRO RUNNING SNEAKERS
135                     SUEDE HIGH-TOPS
136                 SUEDE STRAP SANDALS
137                 MULTIPIECE SNEAKERS
138                  TOPSTITCH SNEAKERS
139                      RETRO SNEAKERS
140             RETRO HIGH TOP SNEAKERS
141         MULTI-PIECED RETRO SNEAKERS
142              TASSEL LEATHER LOAFERS
143                 MOC-TOE SUEDE BOOTS
144                       STRAP SANDALS
145                SUEDE RETRO SNEAKERS
146                        HIKING BOOTS
147                      SUEDE SNEAKERS
148    FAUX SHEARLING LINED SUEDE BOOTS
149                     CHUNKY SNEAKERS
150          DOUBLE STRAP SUEDE SANDALS
151    CHUNKY SOLE CANVAS LACE-UP BOOTS
152                 SUEDE PENNY LOAFERS
153           ADHERENT STRIPES SNEAKERS
154                 MULTIPIECE SNEAKERS
155       CHUNKY SOLE HIGH TOP SNEAKERS
156      CONTRAST SOLE LEATHER SNEAKERS
157              SUEDE RUNNING SNEAKERS
158                WOVEN LEATHER SLIDES
159                      SUEDE SNEAKERS
228         HERRINGBONE TEXTURED JACKET
Name: name, dtype: object

In [13]:
#
df.head(1)

,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,category,section
0,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19,jackets,MAN

In [14]:
## How many section categories?
df.section.unique()

array(['MAN', 'WOMAN'], dtype=object)

In [15]:
df.columns

Index(['Product Position', 'Promotion', 'Product Category', 'Seasonal',
       'Sales Volume', 'brand', 'url', 'sku', 'name', 'description', 'price',
       'currency', 'scraped_at', 'category', 'section'],
      dtype='object')

In [16]:
## Section wise what is the average price, total sales and product count?
df.groupby(['section']).agg(
    avg_price = ('price','mean'),
    total_sales = ('Sales Volume', 'sum'),
    product_count = ('sku', 'count')
    
)

         avg_price  total_sales  product_count
section
MAN      91.824587       396199            218
WOMAN    50.525882        63374             34

In [17]:
## what is the average price, total sales and product count by section and category?
df.groupby(['section','category']).agg(
    avg_price = ('price','mean'),
    total_sales = ('Sales Volume', 'sum'),
    product_count = ('sku', 'count')
    
)

                   avg_price  total_sales  product_count
section category
MAN     jackets   105.757929       259468            140
        jeans      63.923750        13320              8
        shoes      64.873548        57906             31
        sweaters   75.927143        11868              7
        t-shirts   67.427813        53637             32
WOMAN   sweaters   50.525882        63374             34

In [18]:
## Which categories were promoted the most compared to others?
df[df['Promotion'] == 'Yes'].groupby(['category','Promotion'])['sku'].count().sort_values(ascending = False)

category  Promotion
jackets   Yes          68
sweaters  Yes          18
shoes     Yes          16
t-shirts  Yes          15
jeans     Yes           3
Name: sku, dtype: int64

In [19]:
## How many products were promoted in each section ?
df.groupby(['section','Promotion'])['sku'].count()

section  Promotion
MAN      No           115
         Yes          103
WOMAN    No            17
         Yes           17
Name: sku, dtype: int64

In [20]:
## Which category brings high sales?
df.nlargest(1,'price')

,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,category,section
13,Front of Store,Yes,Clothing,Yes,729,Zara,https://www.zara.com/us/en/cropped-leather-jac...,323134418-800-3,CROPPED LEATHER JACKET,Leather jacket. Cropped length. Lapel collar a...,439.0,USD,2024-02-19,jackets,MAN

In [21]:
# Total number of products
df['sku'].nunique()

228

In [22]:
#Total products and Total products per category
df.groupby('category')['sku'].count()

category
jackets     140
jeans         8
shoes        31
sweaters     41
t-shirts     32
Name: sku, dtype: int64

In [23]:
df.head()

,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,category,section
0,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19,jackets,MAN
1,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,169.00,USD,2024-02-19,jackets,MAN
2,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,129.00,USD,2024-02-19,jackets,MAN
3,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,129.00,USD,2024-02-19,jackets,MAN
4,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,139.00,USD,2024-02-19,jackets,MAN

In [24]:
#Top 2 expensive products in each category

# .loc is short for label location
# Input: Give me the value for column product name at Row 0
df.loc[0, 'name']

'BASIC PUFFER JACKET'

In [25]:
df.head(1)

,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,price,currency,scraped_at,category,section
0,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,19.99,USD,2024-02-19,jackets,MAN

In [26]:
# iloc 
# Give me what value is sitting on x row and y column
# row, column
df.iloc[0,2]

'Clothing'

In [27]:
# lambda input: expression
df['price_category'] = df['price'].apply(lambda p: "Expensive" if p > 100 else "Affordable")

In [28]:
## Top 2 expensive products in each category
df.groupby('category').apply(lambda x:x.nlargest(2,'price'))[['category','section','name','price']]

/var/folders/7h/5qt05wxn4dqcc5zmk8cj5fb00000gn/T/ipykernel_16408/899302532.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('category').apply(lambda x:x.nlargest(2,'price'))[['category','section','name','price']]

              category section                              name  price
category
jackets  13    jackets     MAN            CROPPED LEATHER JACKET  439.0
         38    jackets     MAN                      SUEDE JACKET  349.0
jeans    201     jeans     MAN            FLARED FIT CARGO JEANS  109.0
         197     jeans     MAN   BAGGY FIT JEANS LIMITED EDITION   69.9
shoes    142     shoes     MAN            TASSEL LEATHER LOAFERS   99.9
         148     shoes     MAN  FAUX SHEARLING LINED SUEDE BOOTS   99.9
sweaters 169  sweaters   WOMAN       CASHMERE BLEND KNIT SWEATER  169.0
         231  sweaters     MAN            CROPPED LEATHER JACKET  169.0
t-shirts 232  t-shirts     MAN      FAUX LEATHER BOXY FIT JACKET  169.0
         235  t-shirts     MAN               DENIM BOMBER JACKET  139.0

In [29]:
df.dtypes

Product Position     object
Promotion            object
Product Category     object
Seasonal             object
Sales Volume          int64
brand                object
url                  object
sku                  object
name                 object
description          object
price               float64
currency             object
scraped_at           object
category             object
section              object
price_category       object
dtype: object

In [30]:
# Do men shop more than women in Zara?
df.groupby('section').agg(
    total_sales_volume = ('Sales Volume', 'sum'),
    total_products = ('sku', 'count')
)

         total_sales_volume  total_products
section
MAN                  396199             218
WOMAN                 63374              34